name: "record-deployment"
description: "Record deployment of an application to an environment"
branding:
  icon: "check"
  color: "green"
inputs:
  PACT_BROKER_BASE_URL:
    description: "The url of your pact broker"
    required: true
  PACT_BROKER_TOKEN:
    description: "Your pact broker token"
    required: true
  application_name:
    description: "The name of your application (usually project name)"
    required: true
  version:
    description: "The version of your application (defaults to latest)"
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/recordDeployment.sh
      shell: bash
