name: "publish-provider-contract"
description: "Publishes an OAS and test results to Pactflow (requires checkout action first)"
branding:
  icon: "upload"
  color: "green"
inputs:
  PACT_BROKER_BASE_URL:
    description: "The url of your pact broker"
    required: true
  PACT_BROKER_TOKEN:
    description: "Your pact broker token"
    required: true
  application_name:
    description: "The name of your application (usually project name)"
    required: true
  oas_file:
    description: "Location of the OAS file"
    required: true
  oas_file_content_type:
    description: "Content type of the OAS file (optional, default 'application/yaml')"
    required: false
  results_file:
    description: "Location of the test evidence file"
    required: true
  version:
    description: "Version to publish"
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/publishOAS.sh
      shell: bash
