name: pact-cli
description: A standalone pact command line executable using the ruby pact implementation and Traveling Ruby
runs:
  using: "composite"
  steps:
  # https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions#runsstepsrun
    # install pact-broker-cli (rust)
    - uses: pact-foundation/pact-broker-cli@main
    # install pact-ruby-standalone
    - run: $GITHUB_ACTION_PATH/cli.sh
      shell: bash
    - name: add to path if windows
      if: runner.os == 'windows'
      shell: powershell
      run: |
        "$pwd\pact\bin\" >> $env:GITHUB_PATH
