name: "publish-pact-files"
description: "Publishes a Pact file to a Pact Broker (requires checkout action first)"
branding:
  icon: "upload"
  color: "green"
inputs:
  pact_cli_image:
    description: "Docker image to use for running pact-cli commands (defaults to the official PactFlow image)"
    required: false
  pact_cli_image_tag:
    description: "Tag of the Docker image to use for running pact-cli commands (default: latest)"
    required: false
  broker_url:
    description: "The url of your pact broker"
    required: true
  pactfiles:
    description: "Location of the Pact files"
    required: true
  token:
    description: "Your pact broker token (required for PactFlow)"
  username:
    description: "Your pact broker username"
  password:
    description: "Your pact broker password"
  version:
    description: "Version to publish"
  branch:
    description: "branch to associate version of pact with"
  tag:
    description: "tag to associate version of pact with"
  tag_with_git_branch:
    description: "tag pact with git branch"
runs:
  using: "composite"
  steps:
    - run: ${GITHUB_ACTION_PATH}/publishPactfiles.sh
      shell: bash
      env:
        PACT_BROKER_BASE_URL: ${{ inputs.broker_url || env.PACT_BROKER_BASE_URL }}
        PACT_BROKER_TOKEN: ${{ inputs.token || env.PACT_BROKER_TOKEN }}
        PACT_BROKER_USERNAME: ${{ inputs.username || env.PACT_BROKER_USERNAME }}
        PACT_BROKER_PASSWORD: ${{ inputs.password || env.PACT_BROKER_PASSWORD }}
        pact_cli_image: ${{ inputs.pact_cli_image || env.pact_cli_image }}
        pact_cli_image_tag: ${{ inputs.pact_cli_image_tag }}
        pactfiles: ${{ inputs.pactfiles || env.pactfiles }}
        version: ${{ inputs.version || env.version }}
        tag: ${{ inputs.tag || env.tag }}
        branch: ${{ inputs.branch || env.branch }}
        tag_with_git_branch: ${{ inputs.tag_with_git_branch }}
