name: "publish-pact-files"
description: "Publishes a Pact file to Pactflow (requires checkout action first)"
branding:
  icon: "upload"
  color: "green"
inputs:
  PACT_BROKER_BASE_URL:
    description: "The url of your pact broker"
    required: true
  PACT_BROKER_TOKEN:
    description: "Your pact broker token"
    required: true
  application_name:
    description: "The name of your application (usually project name)"
    required: true
  pactfiles:
    description: "Location of the Pact files"
    required: true
  version:
    description: "Version to publish"
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/publishPactfiles.sh
      shell: bash
