name: "can-i-deploy"
description: "Checks other applications with this tag are compatible with yours"
branding:
  icon: "check"
  color: "green"
inputs:
  PACT_BROKER_BASE_URL:
    description: "The url of your pact broker"
    required: true
  PACT_BROKER_TOKEN:
    description: "Your pact broker token"
    required: true
  application_name:
    description: "The name of your application (usually project name)"
    required: true
  version:
    description: "The version of your application (defaults to latest)"
    required: false
  latest:
    description: "The latest tag value of your application (i.e. 'test' or 'stage')"
    required: false
  to:
    description: "The tag you wish to deploy to (test / stage / prod etc...)"
    required: true
  retry_while_unknown:
    description: |
      Optional (default 0): the number of times to retry while there is an unknown
      verification result (ie. the provider verification is likely still running)
    required: false
  retry_interval:
    description: |
      Optional (default 10): The time between retries in seconds.
      Use in conjunction with --retry-while-unknown
    required: false
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/canideployTo.sh
      shell: bash
