name: "delete-branch"
description: "Deletes a pacticipant branch"
branding:
  icon: "check"
  color: "green"
inputs:
  pact_cli_image:
    description: "Docker image to use for running pact-cli commands"
    required: false
  broker_url:
    description: "The url of your pact broker"
    required: true
  token:
    description: "Your pact broker token (required for PactFlow)"
  username:
    description: "Your pact broker username"
  password:
    description: "Your pact broker password"
  application_name:
    description: "The name of your application (usually project name)"
    required: true
  branch:
    description: "The branch of your application to delete"
    required: true
  error_when_not_found:
    description: "Raise an error if the branch that is to be deleted is not found"
    required: false
    type: choice
    options:
      - true
      - false
runs:
  using: "composite"
  steps:
    - run: ${GITHUB_ACTION_PATH}/deleteBranch.sh
      shell: bash
      env: 
        PACT_BROKER_BASE_URL: ${{ inputs.broker_url || env.PACT_BROKER_BASE_URL }} 
        PACT_BROKER_TOKEN: ${{ inputs.token || env.PACT_BROKER_TOKEN }} 
        PACT_BROKER_USERNAME: ${{ inputs.username || env.PACT_BROKER_USERNAME }} 
        PACT_BROKER_PASSWORD: ${{ inputs.password || env.PACT_BROKER_PASSWORD }} 
        pact_cli_image: ${{ inputs.pact_cli_image || env.pact_cli_image }}
        application_name: ${{ inputs.application_name || env.application_name }}
        version: ${{ inputs.version || env.version }}
        branch: ${{ inputs.branch || env.branch }}
        error_when_not_found: ${{ inputs.error_when_not_found || env.error_when_not_found }}
